/** Única fuente de URLs del sitio. */
export const paths = {
  home: "/",
  story: "/historia",
  whyUs: "/por-que-nosotros",
  locations: "/sedes",
  location: (slug: string) => `/sedes/${slug}`,
  services: "/servicios",
  vip: "/la-cava",
  shop: "/tienda",
  product: (slug: string) => `/tienda/${slug}`,
  cart: "/carrito",
  checkout: "/checkout",
  booking: "/reservar",
  bookingManage: (code: string, token: string) => `/mi-reserva/${code}?token=${encodeURIComponent(token)}`,
  orderManage: (code: string, token: string) => `/mi-pedido/${code}?token=${encodeURIComponent(token)}`,
  contact: "/contacto",
  club: "/club-jack",
  login: "/ingresar",
  register: "/registrarme",
  account: "/mi-cuenta",
  legal: (slug: string) => `/legal/${slug}`,
  admin: "/admin",
} as const;
